server:
  port: 8091

logging:
  config: file:/config/logback.xml
  file:
    path: /export/log/fedlearn-frontend/
    name: fedlearn-frontend_detail.log


baseUrl:
  "http://127.0.0.1:8092/api/"

spring:
  profiles:
    active: "@profileName@"
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:conf/fl.db
    username:
    password:
caffeinecache:
  timeToLive: 1800
  maxSize: 500



jdchain:
  available: false
  gateway_ip: "127.0.0.1" #连接网关服务IP
  gateway_port: "32002" #连接网关服务端口
  gateway_secure: "false" #网关服务是否开启tls(false:不支持 true:支持),目前暂不支持tls
  user_pubkey: "abc" #用户公钥
  user_privkey: "abc" #用户私钥
  user_privpwd: "abc" #解密私钥密码
  ledger_address: "abc" #账本Hash,用于多账本时配置，如果仅有一个账本，可不配置
  contract_address: "abc" #合约地址
  data_account_address: "abc" #数据账户地址
  event_account_address: "abc" #事件账户地址
  user_table_address: "abc" #user信息的数据账户地址
  task_table_address: "abc" #task信息的数据账户地址
  train_table_address: "abc" #train信息的数据账户地址
  merchant_table_address: "abc" #merchant数据账户地址
  default_user: "admin" #默认的用户名
  default_password: "666666" #默认用户的密码

