server:
  port: 8091


spring:
  profiles:
    active: "@profileName@"
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:/export/Config/fl.db
    username:
    password:
caffeinecache:
  timeToLive: 1800
  maxSize: 500

jdchain:
  available: false
  gateway_ip: "116.196.65.147"  #连接网关服务IP
  gateway_port: "31482"     #连接网关服务端口
  gateway_secure: "false"  #网关服务是否开启tls(false:不支持 true:支持),目前暂不支持tls
  user_pubkey: "3snPdw7i7PWGBUCStmDzTyUo6LbtnmBsyj9qp9KAx7A8bgV2hjzUcD" #用户公钥
  user_privkey: "177gjwwZM6LZsmy9KTxqAHKtFJzeB6yNY1izy8xrrViGKPnKRTNytMHBe1qHxnyNYMWWVaT" #用户私钥
  user_privpwd: "DAc48C8t1V1UJk6ZvNQYXzEPbHgG3H8eTzGBNtZZMNPC"   #解密私钥密码
  ledger_address: "j5myEq58QDksALAZwkwKzh2iaJ1JxwS2dipoLsyxNsF7PN"  #账本Hash,用于多账本时配置，如果仅有一个账本，可不配置
  contract_address: "LdeNyKwXLBaPgXRkWwfYyeEGW76Q5CCBSvjoL" #合约地址
  data_account_address: "LdeNpPdvdiUU25z7XmURGTo6SMJSZTtCNaDdq" #数据账户地址
  event_account_address: "LdeNuMsX2XruTt3syXL35ZTSiN2Jj7pbgHUx1"  #事件账户地址
  user_table_address: "LdeNqVMnPgSReaX6v2AMyehNvKk11VNXpN3Fm"  #user信息的数据账户地址
  task_table_address: "LdeNtHWScYd2QZd5W6ZrW8G4ynRxF9S76VxAK"  #task信息的数据账户地址
  train_table_address: "LdeNix8xoZonTWLsdT2CDMDZUt7exfUWmfkFc"  #train信息的数据账户地址
  merchant_table_address: "LdeNvzcpHdhixg5H1y7iAvdLRPex3Zobrgmsc"  #merchant数据账户地址
  default_user: "superadmin" #默认的用户名
  default_password: "666666"  #默认用户的密码

